sneakers/config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  resources :users, only: [:show, :new, :create] do
    resources :shoes, only: [:new, :create]
  end

  resource :session, :only => [:new, :create, :destroy]

end

sneakers/app/models/shoe.rb
class Shoe < ActiveRecord::Base
  validates :brand, :model, :year, :purchase_date,
            :presence => :true
  belongs_to :user
end

sneakers/app/models/user.rb
class User < ActiveRecord::Base

  has_many :shoes

  validates :username, length: { in: 6..20 }
end

sneakers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  private

  def sign_in(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def sign_out
    @current_user = nil
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def signed_in_user?
    !!current_user
  end
  helper_method :signed_in_user?

  def require_login
    unless signed_in_user?
      flash[:error] = "Please sign in"
      redirect_to root_url
    end
  end

  def require_current_user
    unless params[:id] == current_user.id.to_s
      flash[:error] = "Access denied"
      redirect_to root_url
    end
  end
end

sneakers/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, :only => [:new, :create]

  def create
    @user = User.find_by_email(params[:email])
    if @user
      sign_in(@user)
      flash[:success] = "Successfully signed in"
      redirect_to user_path(@user)
    else
      flash.now[:error] = "Failed to sign in"
      render :new
    end
  end

  def destroy
    sign_out
    flash[:success] = "Signed out"
    redirect_to root_url
  end
end

sneakers/app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

  def new
    @shoe = User.find(params[:user_id]).shoes.build
  end

  def create
    @shoe = User.find(params[:user_id]).shoes.build(shoe_params)
    if @shoe.save
      flash[:success] = "New shoes, my favorite!"
      redirect_to @shoe.user
    else
      flash.now[:error] = "You're probably missing something."
      render :new
    end
  end

  private

  def shoe_params
    params.require(:shoe).permit(:brand, :model, :year, :purchase_date)
  end
end

sneakers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, :only => [:new, :create, :index]
  before_action :require_current_user, :only => [:edit, :update, :destroy]

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      flash[:success] = "Welcome, new user!"
      redirect_to @user
    else
      flash.now[:error] = "Something went wrong."
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

sneakers/app/helpers/application_helper.rb
module ApplicationHelper
end

sneakers/app/helpers/sessions_helper.rb
module SessionsHelper
end

sneakers/app/helpers/shoes_helper.rb
module ShoesHelper
end

sneakers/app/helpers/users_helper.rb
module UsersHelper
end

sneakers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sneakers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

sneakers/app/views/shoes/new.html.erb
<h1>Add a pair of shoes to your closet, <%= @shoe.user.username %>.</h1>

<%= form_for [@shoe.user, @shoe] do |f| %>
  Brand<br>
  <%= f.text_field :brand %>
  <br><br>
  Model<br>
  <%= f.text_field :model %>
  <br><br>
  Year<br>
  <%= f.select :year, ((Time.zone.now.year - 100)..(Time.zone.now.year + 1)).to_a.reverse %>
  <br><br>
  Purchase Date<br>
  <%= f.date_select :purchase_date %>
  <br><br>
  <%= f.submit %>
<% end %>

sneakers/app/views/users/new.html.erb
<h1>Create a new user</h1>

<%= form_for @user do |f| %>
  Username <br>
  <%= f.text_field :username %>
  <br><br>
  Email <br>
  <%= f.text_field :email %>
  <br><br>
  <%= f.submit %>
<% end %>

<%= link_to "Login", new_session_path %>

sneakers/app/views/users/show.html.erb
<h1><%= @user.username %>'s shoe closet</h1>

<table>
  <tr>
    <th>Brand</th>
    <th>Model</th>
    <th>Year</th>
    <th>When I Bought It</th>
  </tr>
  <% current_user.shoes.each do |shoe| %>
  <tr>
    <th><%= shoe.brand %></th>
    <th><%=shoe.model %></th>
    <th><%=shoe.year %></th>
    <th><%=shoe.purchase_date %></th>
  </tr>
  <% end %>
</table>

<br>
<%= link_to "Add a pair of shoes!", new_user_shoe_path(@user) %>